### ISSUE TITLE
Can not login to Honeywell Home

### ISSUE THREAD

**Issue by glenncs** [dbarentine/udi-honeywellhome-poly#4]
Hello,
I have reached the step where you say:  This will intiate a login process with Honeywell Home. You will need to enter your Honeywell Home user (email) and password.

I can not find a way to create an account on Honeywell Home. I have searched and searched.   I have an account on: https://mytotalconnectcomfort.com/ and tried this login and failed.  I also tried the login that I created for the Honeywell Home Developer site.

Is it possible that the documentation is out of date?  Should it be pointing to mytotalconectcomfort.com now??  If so, the login does not work.

Thanks!

**Comment by colecaz** [comment]
You have to create the account via the app.  There is no web page for signup.

**Comment by glenncs** [comment]
Argh.  I had initially installed and registered the Honeywell Home Total Connect.  Have now installed and registered with the Honeywell Home App.  Two new thermostats are showing up in the app.  However, when I login to the Honeywell Home API page it finds zero devices.  See images below.
I purchased the Honeywell Home RTH9585WF1004 Wi-Fi Smart Color Thermostat.  Should be supported.  Right??

![Screenshot 2020-07-03 at 10 17 36 AM](https://user-images.githubusercontent.com/67776551/86488911-6daa5b80-bd17-11ea-82a5-41881ea4dc61.png)

![image](https://user-images.githubusercontent.com/67776551/86488924-769b2d00-bd17-11ea-9aed-2522733cc9f1.png)

**Comment by colecaz** [comment]
Are they still registered in Honeywell Total Connect?  I believe they have to be removed from there first. Cole From: glenncsSent: Friday, July 3, 2020 10:30 AMTo: dbarentine/udi-honeywellhome-polyCc: Cole Cunningham; CommentSubject: Re: [dbarentine/udi-honeywellhome-poly] Can not login to Honeywell Home (#4) Argh. I had initially installed and registered the Honeywell Home Total Connect. Have now installed and registered with the Honeywell Home App. Two new thermostats are showing up in the app. However, when I login to the Honeywell Home API page it finds zero devices. See images below.I purchased the Honeywell Home RTH9585WF1004 Wi-Fi Smart Color Thermostat. Should be supported. Right??—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by glenncs** [comment]
Hello.  I unregistered one thermostat from Total Connect and then attempted to register it directly with Honeywell Home.  No luck as it is not on the list and I even tried to fake it out by selecting all of the available thermostats and seeing if I could connect that way.  The only way, and confirmed by phone from Honeywell, is to import Total Connect Thermostats into Honeywell Home.  I have searched through the forums.  It appears that at least two individuals did manage to get it to work.  They have older thermostats of the same generation as mine.  Any other ideas?  Sorry to bug you, but this is a very popular Honeywell thermostat that is still being sold.  Thanks!
Here is the forum entry I was referring to: https://forum.universal-devices.com/topic/28877-honeywell-home-polyglot-cloud/?tab=comments#comment-282242

**Comment by colecaz** [comment]
I didn’t recognize the model number you noted, but I’ll bet it’s of the same generation as I started out trying.  I had three RTH6580WF’s and never had any luck with them.  They didn’t show up in the API, so I bought a T6Pro.  It worked perfectly.  But as I remember, when I imported it into the Polyglot server, it brought the 6580’s along…  So even though they showed up, they didn’t program correctly or completely and I gave up on them and went to all T6Pro’s.  They’ve been working flawlessly. Here’s an interesting thread if you haven’t run across it already.https://forum.universal-devices.com/topic/28877-honeywell-home-polyglot-cloud/ Cole From: glenncsSent: Friday, July 3, 2020 4:08 PMTo: dbarentine/udi-honeywellhome-polyCc: Cole Cunningham; CommentSubject: Re: [dbarentine/udi-honeywellhome-poly] Can not login to Honeywell Home (#4) Hello. I unregistered one thermostat from Total Connect and then attempted to register it directly with Honeywell Home. No luck as it is not on the list and I even tried to fake it out by selecting all of the available thermostats and seeing if I could connect that way. The only way, and confirmed by phone from Honeywell, is to import Total Connect Thermostats into Honeywell Home. I have searched through the forums. It appears that at least two individuals did manage to get it to work. They have older thermostats of the same generation as mine. Any other ideas? Sorry to bug you, but this is a very popular Honeywell thermostat that is still being sold. Thanks!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dbarentine** [comment]
@glenncs I apologize for not being more responsive. Between my day job, some COVID related issues, and now the wildfires in Oregon I have not been paying attention to these projects or the Github notifications for them.

I have not had a chance yet to work with thermostats outside of the T series ones. @colecaz has actually sent me one of the RTH6580WF's to figure out how to build compatibility with them but I've had very little time over the last number of months to look at it out.

So the intent is obviously to support as many thermostats as possible but as this is a side project that ability is limited by the amount of time I have available.

**Comment by glenncs** [comment]
Hello Dane,

No worries.  I ended up returning the older thermostat and purchased a T9.

Thanks for checking back.

 

Regards,

Glenn

**Comment by bhogan71** [comment]
I having a challenge when I put the Honeywell app keys in and it gives me the login page to log into total connect does not take my credentials? I know they are right i can login into https://mytotalconnectcomfort.com/. I must be doing something wrong, any ideas? Bernie

Honeywell Logo
Sorry, we cannot find a user with these credentials.
Log in to access.
Email

Password

LOG IN
Forgot Password?

**Comment by glenncs** [comment]
Hello,

First, you have my empathy.  Documentation is splattered everywhere and is poor.  I remember having a lot of grief with setting up my thermostat, and unfortunately don’t remember the details.

But!! I did find my notes where I combined multiple documents from multiple sources.

 

A couple of things:

1.	You must use one of the “newer” models.  I had to return what I thought was a newer model and purchased a T9.
2.	Just to confuse things there are two Honeywell portals.  I believe one is total connect and the other is Honeywell home.  You must use the newer portal.  Looking at my phone app and notes  it is Honeywell Home.  This probably means Total Connect is for the previous generation of Thermostats and it does not work.

 

Hope it helps a bit.

 

Regards,

Glenn

**Comment by dbarentine** [comment]
@bhogan71 @glenncs Sorry this got covered in the UDI forums but I forgot to update it here.

There are actually three different Honeywell APIs and yes documentation is poor. The three APIs in some cases overlap which makes it confusing as well. But those APIs are:

- Total Connect 2 (TC2) - This is mostly about security devices although it does have some thermostat integration as well. There is a separate node server to handle TC2 security devices.
- Total Connect Comfort (TCC) - This is for older thermostats. There is no node server for this currently.
- Honeywell Home - This nodeserver and is for the newer thermostats such as the T9 and T10.

To confuse matters further there was a period where Honeywell was allowing you to import your TCC thermostats in to Honeywell Home. This would have been nice as this node server could have supported both the newer and older versions. But they ended up removing that functionality because it was causing issues I think with their utility customers.

So as of right now it only supports the new thermostats. From the last response that I missed it looks like you were logging into the https://mytotalconnectcomfort.com/ portal. That'd for TCC and due to the Honeywell change no longer supported in the Honeywell Home API that we are using.
